[metadata]
name = condiment
description = Conditionally include code according to environment variables
long_description = file: README.md
long_description_content_type = text/markdown; charset=UTF-8
url = http://github.com/tito/condiment
author = Mathieu Virbel
author_email = mat@kivy.org
license = zlib
license_file = LICENSE
keywords = python, preprocessor, meta, condiment, conditional
classifiers =
    Programming Language :: Python
    Programming Language :: Python :: 2.7
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.3
    Development Status :: 4 - Beta
    Intended Audience :: Developers
    License :: OSI Approved :: zlib/libpng License
    Operating System :: OS Independent
    Topic :: Software Development :: Pre-processors
    Topic :: Software Development :: Libraries :: Python Modules
    Topic :: Software Development :: Code Generators

[options]
zip_safe = False
packages = find:
platforms = any
include_package_data = True
python_requires = >=3.8
